name: goal_emb
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.6
  - numpy
  - progressbar2
  - pytorch-cpu=0.3.1=py36_cpu_2
  - pip:
    - visdom
    - git+https://github.com/tesatory/mazebase.git
